name: Updater

on:
  schedule:
    - cron: '*/5 7-20 * * 1-5' # Every 5 minutes from 7:00 to 20:00, from Mon to Fri.
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Give permision to backend script
      run: chmod +x backend.sh

    - name: Run backend script
      run: ./backend.sh

    - name: Commit changed file
      uses: EndBug/add-and-commit@v9
      with:
        add: 'data.tsv'
        message: 'Update data.tsv'
